---
- src: https://github.com/Oefenweb/ansible-swapfile
  name: swapfile
- src: https://github.com/caktus/tequila-common
  version: v0.8.0
- src: https://github.com/caktus/tequila-dokku
  version: v0.2.0
