---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws.yml
    - vars/aws_secrets.yml
  tasks:
    - name: get admin's public ip address
      ipify_facts:
    - name: fetch cloudformation template.
      get_url:
        url: https://s3.amazonaws.com/dokku-aws/dokku_stack.json
        dest: files/cf_template.json
    - name: Ensure cloudformation is up
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: present
        region: "{{ aws_region }}"
        template: files/cf_template.json
        template_parameters:
          DokkuHostname: "{{ stack_name }}.{{ zone }}"
          KeyName: "{{ key_name }}"
          SshCidr: "{{ ipify_public_ip }}/32"
      register: cloudformation
    - name: "Remove {{ stack_name }} stack"
      route53:
        profile: "{{ aws_dns_profile }}"
        command: delete
        overwrite: true
        zone: "{{ zone }}"
        record: "{{ stack_name }}.{{ zone }}"
        type: A
        value: "{{ cloudformation.stack_outputs.PublicIP }}"
    - name: Destroy cloudformation to create ec2, security group, and EIP.
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: absent
        region: "{{ aws_region }}"
